# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f8a13fb5cc139b476b5fc562dc6c4ff8296aa58d770ce792005d063f63261aa2e5696857445612a3bbb95b0d0a8c0e5b0ab5d6fe51c4fe52abca710cf7c36e4

test:
  secret_key_base: 3ebef3e55aa48e04ab6f5950474366d2e3b6527d3dcd6a67504958c5b77465133e2daf8a4fa568a1d30514c37aad78603e7f24d2c24b055daf3cbae8f08a4dfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
